<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class EquipeSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'slug'          => 'joao-silva',
                'nome'          => 'Dr. João Silva',
                'cargo'         => 'Sócio Fundador',
                'especialidade' => 'Direito Civil & Empresarial',
                'oab'           => 'OAM/BEI 0012',
                'bio'           => 'Com mais de 20 anos de experiência jurídica, o Dr. João Silva fundou o escritório em 2009 com a missão de oferecer serviços jurídicos de excelência à comunidade da Beira e de Moçambique.',
                'formacao'      => 'Licenciatura em Direito — Universidade Eduardo Mondlane, 2003',
                'pos_graduacao' => 'Pós-Graduação em Direito Empresarial — ISCED, 2006',
                'areas'         => json_encode(['Direito Civil', 'Direito Empresarial', 'Contratos', 'Arbitragem']),
                'idiomas'       => json_encode(['Português', 'Inglês', 'Francês']),
                'foto'          => 'assets/images/equipe/joao-silva.jpg',
                'email'         => 'joao.silva@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 1,
                'ativo'         => 1,
                'ordem'         => 1,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'slug'          => 'ana-ferreira',
                'nome'          => 'Dra. Ana Ferreira',
                'cargo'         => 'Sócia',
                'especialidade' => 'Direito Penal',
                'oab'           => 'OAM/BEI 0034',
                'bio'           => 'A Dra. Ana Ferreira é uma das mais respeitadas advogadas penalistas de Moçambique, com mestrado em Direito Penal pela Universidade de Coimbra.',
                'formacao'      => 'Licenciatura em Direito — Universidade Católica de Moçambique, 2005',
                'pos_graduacao' => 'Mestrado em Direito Penal — Universidade de Coimbra, 2009',
                'areas'         => json_encode(['Direito Penal', 'Crimes Económicos', 'Direito Processual Penal']),
                'idiomas'       => json_encode(['Português', 'Inglês']),
                'foto'          => 'assets/images/equipe/ana-ferreira.jpg',
                'email'         => 'ana.ferreira@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 1,
                'ativo'         => 1,
                'ordem'         => 2,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'slug'          => 'carlos-matos',
                'nome'          => 'Dr. Carlos Matos',
                'cargo'         => 'Advogado Sénior',
                'especialidade' => 'Direito Empresarial',
                'oab'           => 'OAM/BEI 0078',
                'bio'           => 'O Dr. Carlos Matos é especialista em Direito Empresarial, com vasta experiência em assessoria a PMEs e grandes empresas nacionais e internacionais.',
                'formacao'      => 'Licenciatura em Direito — Universidade Pedagógica, 2008',
                'pos_graduacao' => 'MBA em Gestão e Direito Empresarial — ISBE, 2012',
                'areas'         => json_encode(['Direito Empresarial', 'Fusões & Aquisições', 'Due Diligence', 'DUAT']),
                'idiomas'       => json_encode(['Português', 'Inglês', 'Espanhol']),
                'foto'          => 'assets/images/equipe/carlos-matos.jpg',
                'email'         => 'carlos.matos@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 1,
                'ativo'         => 1,
                'ordem'         => 3,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'slug'          => 'maria-sousa',
                'nome'          => 'Dra. Maria Sousa',
                'cargo'         => 'Advogada',
                'especialidade' => 'Direito de Família',
                'oab'           => 'OAM/BEI 0105',
                'bio'           => 'A Dra. Maria Sousa dedica a sua prática ao Direito de Família, acompanhando com sensibilidade e profissionalismo processos de divórcio, regulação do poder paternal e adoção.',
                'formacao'      => 'Licenciatura em Direito — Universidade Eduardo Mondlane, 2012',
                'pos_graduacao' => 'Especialização em Direito de Família e Menores — UCM, 2015',
                'areas'         => json_encode(['Direito de Família', 'Direito de Menores', 'Partilhas', 'Adoção']),
                'idiomas'       => json_encode(['Português', 'Inglês']),
                'foto'          => 'assets/images/equipe/maria-sousa.jpg',
                'email'         => 'maria.sousa@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 1,
                'ativo'         => 1,
                'ordem'         => 4,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'slug'          => 'pedro-nhambe',
                'nome'          => 'Dr. Pedro Nhambe',
                'cargo'         => 'Advogado',
                'especialidade' => 'Direito Laboral',
                'oab'           => 'OAM/BEI 0132',
                'bio'           => 'O Dr. Pedro Nhambe é especializado em Direito Laboral, prestando assessoria jurídica a empresas e trabalhadores.',
                'formacao'      => 'Licenciatura em Direito — Universidade Zambeze, 2015',
                'pos_graduacao' => null,
                'areas'         => json_encode(['Direito Laboral', 'Relações Colectivas', 'Processos Disciplinares']),
                'idiomas'       => json_encode(['Português', 'Inglês', 'Sena']),
                'foto'          => 'assets/images/equipe/pedro-nhambe.jpg',
                'email'         => 'pedro.nhambe@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 0,
                'ativo'         => 1,
                'ordem'         => 5,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
            [
                'slug'          => 'lucia-chongo',
                'nome'          => 'Dra. Lúcia Chongo',
                'cargo'         => 'Advogada',
                'especialidade' => 'Direito Administrativo',
                'oab'           => 'OAM/BEI 0149',
                'bio'           => 'A Dra. Lúcia Chongo actua na área do Direito Administrativo, representando clientes em processos de licenciamento e contratação pública.',
                'formacao'      => 'Licenciatura em Direito — Universidade Eduardo Mondlane, 2016',
                'pos_graduacao' => null,
                'areas'         => json_encode(['Direito Administrativo', 'Contratação Pública', 'Direito Fiscal']),
                'idiomas'       => json_encode(['Português', 'Inglês']),
                'foto'          => 'assets/images/equipe/lucia-chongo.jpg',
                'email'         => 'lucia.chongo@advocacia.co.mz',
                'linkedin'      => '#',
                'destaque'      => 0,
                'ativo'         => 1,
                'ordem'         => 6,
                'created_at'    => $now,
                'updated_at'    => $now,
            ],
        ];

        $this->db->table('equipe')->insertBatch($data);
    }
}